fix: setup go with the correct version in nix GHA (#1838)
The nix GHA is
[failing](https://github.com/open-component-model/ocm/actions/runs/22347176511/job/64664675329)
since some time because

```
go: go.mod requires go >= 1.25.7 (running go 1.25.6; GOTOOLCHAIN=local)
error: Cannot build '/nix/store/1arisjbbjkpskw54dw6bc6yxk0n6l5n5-ocm-0.38.0-dev-go-modules.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/is2w1y4jiq77cs23sn4p80ghg7dpks4g-ocm-0.38.0-dev-go-modules
       Last 8 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/dgf3q1lwrymkbkrqfjhl3khxc5n1qmjw-4bll3adr8nm188wb6r8i22ga5czqvpm5-source
       > source root is 4bll3adr8nm188wb6r8i22ga5czqvpm5-source
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > go: go.mod requires go >= 1.25.7 (running go 1.25.6; GOTOOLCHAIN=local)
```

Currently, `go` is installed via `nix` and apparently there is no
version `1.25.7` available.

By using go version `1.26` the workflow runs again

Signed-off-by: Frederic Wilhelm <frederic.wilhelm@sap.com>